### ISSUE TITLE
Missing method: hasPackage()

### ISSUE THREAD

**Issue by michaelspiss** [Solution10/auth#2]
The method hasPackage() as used in the last example of the [Managing the packages on a user](https://github.com/solution10/auth/wiki/Permissions#managing-the-packages-on-a-user) section does not exist in the Auth class. I'd love to open a pull request with a fix, but I'd need to know if this is a mistake in the docs or simply a missing method.

**Comment by alexgisby** [comment]
Great spot, thanks very much @michaspiss ! Have now added that method in #5 

I'm going to tag a release up as v1.3.0 which contains both this and the solution to #3 so you should just be a `composer update` away from getting things fixed.

Thanks very much again for taking the time to raise bugs and PR's, it's really appreciated!

**Comment by michaelspiss** [comment]
You are welcome, thanks for creating this awesome package!
